version: '1.22.4'

volumes:
  postgres1-data:
  postgres2-data:
# docker compose up
services:

  postgres1:
    container_name: container-pg1
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mkv
      POSTGRES_PASSWORD: book_server
      POSTGRES_DB: book_database
    volumes:
      - postgres1-data:/var/lib/postgresql/data
    restart: always

 