#version: '1.22.10'


# docker compose up
services:

  postgres1:
    container_name: container-pg1
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: mkv
      POSTGRES_PASSWORD: book_server
      POSTGRES_DB: book_database
    volumes:
      - postgres-data-books:/var/lib/postgresql/data
    restart: always


  books1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books1
    restart: always
    ports:
      - 8080:8080
      - 8081:8081


volumes:
  postgres-data-books:
 